In [29]:
from __future__ import print_function
import torch

In [35]:
x = x.new_ones(5,3,dtype=torch.double)
x = torch.randn_like(x,dtype=torch.float)

In [36]:
x.size()

torch.Size([5, 3])

In [37]:
y = torch.rand(5,3)

In [40]:
print(x + y)

tensor([[ 1.1655,  0.3860,  1.9352],
        [ 0.1563,  1.6478,  1.2236],
        [ 0.5300, -0.9703,  2.3527],
        [-0.4084,  0.9981,  0.6081],
        [-0.9867,  2.0927, -1.2672]])


In [41]:
print(torch.add(x,y))

tensor([[ 1.1655,  0.3860,  1.9352],
        [ 0.1563,  1.6478,  1.2236],
        [ 0.5300, -0.9703,  2.3527],
        [-0.4084,  0.9981,  0.6081],
        [-0.9867,  2.0927, -1.2672]])


In [42]:
result = torch.empty(5,3)
torch.add(x,y,out=result)

tensor([[ 1.1655,  0.3860,  1.9352],
        [ 0.1563,  1.6478,  1.2236],
        [ 0.5300, -0.9703,  2.3527],
        [-0.4084,  0.9981,  0.6081],
        [-0.9867,  2.0927, -1.2672]])

In [43]:
print(result)

tensor([[ 1.1655,  0.3860,  1.9352],
        [ 0.1563,  1.6478,  1.2236],
        [ 0.5300, -0.9703,  2.3527],
        [-0.4084,  0.9981,  0.6081],
        [-0.9867,  2.0927, -1.2672]])


In [44]:
print(y)

tensor([[0.3075, 0.1738, 0.4184],
        [0.0536, 0.8646, 0.9479],
        [0.0239, 0.1962, 0.3847],
        [0.9295, 0.0801, 0.9702],
        [0.2402, 0.8041, 0.1428]])


In [45]:
y.add_(x)
print(y)

tensor([[ 1.1655,  0.3860,  1.9352],
        [ 0.1563,  1.6478,  1.2236],
        [ 0.5300, -0.9703,  2.3527],
        [-0.4084,  0.9981,  0.6081],
        [-0.9867,  2.0927, -1.2672]])


In [46]:
x = torch.randn(4,4)
print("x:{}".format(x))

x:tensor([[-2.5186,  2.1582, -1.7363,  0.6393],
        [-1.2611,  0.2048,  0.8537,  0.2720],
        [-0.8043,  0.1469,  0.4372,  0.9881],
        [ 0.7205, -0.2668,  0.7555, -0.3462]])


In [49]:
print(x[:,1])

tensor([ 2.1582,  0.2048,  0.1469, -0.2668])


In [50]:
x = torch.randn(4,4)
y = x.view(16)

In [60]:
print("x.shape:{}".format(x.shape))
print("y.shape:{}".format(y.shape))
print("x:{}".format(x))
print("y:{}".format(y))

x.shape:torch.Size([4, 4])
y.shape:torch.Size([16])
x:tensor([[-0.1783, -1.3417,  2.6178, -1.0827],
        [-0.3004,  0.0146, -0.3457,  1.9796],
        [-0.1285, -1.5420, -1.1219,  1.9897],
        [-0.3688, -1.1646,  0.1036, -0.9551]])
y:tensor([-0.1783, -1.3417,  2.6178, -1.0827, -0.3004,  0.0146, -0.3457,  1.9796,
        -0.1285, -1.5420, -1.1219,  1.9897, -0.3688, -1.1646,  0.1036, -0.9551])


In [61]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0434])
1.043440341949463


In [62]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [63]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [64]:
a.add_(1)
print("a:{}".format(a))
print("b:{}".format(b))

a:tensor([2., 2., 2., 2., 2.])
b:[2. 2. 2. 2. 2.]


In [65]:
import numpy as np

In [67]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [69]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))

tensor([2.0434], device='cuda:0')
tensor([2.0434], dtype=torch.float64)
